CommonPath = ./Common/
ListsPath = ./Lists/
TreesPath = ./Trees/


all: main.c $(ListsPath)LinkedList.c $(CommonPath)Node.c  $(ListsPath)Queue.c $(TreesPath)BinarySearchTree.c
	gcc main.c  $(ListsPath)LinkedList.c $(CommonPath)Node.c $(ListsPath)Queue.c  $(TreesPath)BinarySearchTree.c -o output.exe